## make_pix_timeline.py
# Author: Pedro Feijó de Moraes
#
# Last edited: 2026-06-09
#
# Purpose: Produce the analytical figures + tables for the Pix institutional
#          entry timeline and emit a self-contained Markdown section that is
#          appended to Drafts/Deposit Competition/pix-institutional-timeline.md
#          and compiled to PDF.
#
#   Inputs (BCB/PIX/, produced by scrape_6 / scrape_7):
#     pix_participant_keys_panel.csv   month × ISPB key stock
#     pix_participant_entry.csv        per-ISPB key-based entry month
#     pix_roster_history.csv           roster_date × institution classification
#     pix_participant_timeline.csv     unified (keys ⋈ roster) per institution
#
#   Outputs (Drafts/Deposit Competition/):
#     pix_timeline_figs/*.png          figures
#     _pix_analysis_section.md         markdown fragment (figures + tables)
###─────────────────────────────────────────────────────────────────────────────

import os
import re
import glob
import shutil
import logging

try:
    from utils.venv_guard import ensure_project_venv
except Exception:
    ensure_project_venv = None
if ensure_project_venv is not None:
    ensure_project_venv(__file__)

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

from utils import paths
BASE      = str(paths.OPEN_FINANCE)
PIX_DIR   = str(paths.PIX_DIR)
DRAFTS    = os.path.join(BASE, "Drafts", "Deposit Competition")
FIG_DIR   = os.path.join(DRAFTS, "pix_timeline_figs")
MAIN_MD   = os.path.join(DRAFTS, "pix-institutional-timeline.md")
MARK_START = "<!-- PIX-ANALYSIS:START (auto-generated by analysis_pix_timeline.py — do not edit by hand) -->"
MARK_END   = "<!-- PIX-ANALYSIS:END -->"

# Deposit join (Task 3): conglomerate-level national deposits + CNPJ->conglomerate bridge
DEPOSITS_CSV = os.path.join(BASE, "BCB", "Panel", "deposits_panel.csv")
IF_LIST_DIR  = os.path.join(BASE, "BCB", "Egan_et_al_2025_Rep", "raw", "IF_DATA", "List")
MAND_CSV     = os.path.join(PIX_DIR, "pix_mandatory_institutions.csv")
DEPCLASS_CSV = os.path.join(PIX_DIR, "pix_deposits_by_class.csv")

os.makedirs(FIG_DIR, exist_ok=True)
plt.rcParams.update({"figure.dpi": 150, "font.size": 10, "axes.grid": True,
                     "grid.alpha": 0.3, "axes.spines.top": False, "axes.spines.right": False})
C_MAND, C_FAC, C_NA = "#c0392b", "#2980b9", "#bdc3c7"   # mandatory / voluntary / unclassified
C_DIR, C_IND        = "#16a085", "#8e44ad"


def _anomes_to_period(a):
    a = pd.to_numeric(a, errors="coerce")
    dt = pd.to_datetime(a.astype("Int64").astype("string"), format="%Y%m", errors="coerce")
    return pd.PeriodIndex(dt, freq="M")


def _thousands(x, _):
    if abs(x) >= 1e6:
        return f"{x/1e6:.0f}M"
    if abs(x) >= 1e3:
        return f"{x/1e3:.0f}k"
    return f"{x:.0f}"


def cnpj8_root(x):
    s = re.sub(r"\D", "", str(x))
    return s[:8].zfill(8) if len(s) >= 8 else None


def df_to_md(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    out = ["| " + " | ".join(map(str, cols)) + " |",
           "| " + " | ".join("---" for _ in cols) + " |"]
    for _, r in df.iterrows():
        out.append("| " + " | ".join("" if pd.isna(v) else str(v) for v in r) + " |")
    return "\n".join(out)


def load():
    panel = pd.read_csv(os.path.join(PIX_DIR, "pix_participant_keys_panel.csv"), dtype={"ISPB": str})
    entry = pd.read_csv(os.path.join(PIX_DIR, "pix_participant_entry.csv"), dtype={"ISPB": str})
    tl    = pd.read_csv(os.path.join(PIX_DIR, "pix_participant_timeline.csv"))
    hist  = pd.read_csv(os.path.join(PIX_DIR, "pix_roster_history.csv"), parse_dates=["roster_date"])
    entry["ISPB"] = entry["ISPB"].str.zfill(8)
    return panel, entry, tl, hist


# ── classification label per institution (last known, fallback first) ────────────
def classify(tl: pd.DataFrame) -> pd.DataFrame:
    t = tl.copy()
    t["ispb"] = t["ispb"].astype(str).str.replace(r"\.0$", "", regex=True).str.zfill(8)
    src = t["last_tipo_pix"].fillna(t["first_tipo_pix"])
    t["mv"] = src.map({"obrigatoria": "Obrigatória (mandatory)",
                       "facultativa": "Facultativa (voluntary)"}).fillna("Unclassified")
    s = t["last_spi"].fillna(t["first_spi"])
    t["di"] = s.map({"direta": "Direta (direct)", "indireta": "Indireta (indirect)"}).fillna("Unknown")
    # One row per ISPB: the crosswalk can map two CNPJs to one ISPB, so dedupe and
    # keep a classified row over an unclassified one (sort puts Unclassified last).
    t = t.sort_values("mv").drop_duplicates("ispb", keep="first")
    return t


# ── FIGURES ──────────────────────────────────────────────────────────────────
def fig_adoption_curve(entry):
    p = _anomes_to_period(entry["entry_anomes"]).dropna()
    s = pd.Series(1, index=p).groupby(level=0).sum().sort_index()
    full = pd.period_range(s.index.min(), s.index.max(), freq="M")
    s = s.reindex(full, fill_value=0)
    cum = s.cumsum()
    x = s.index.to_timestamp()
    fig, ax = plt.subplots(figsize=(8, 4.2))
    ax.bar(x, s.values, width=20, color=C_FAC, alpha=0.45, label="New participants (month)")
    ax2 = ax.twinx(); ax2.grid(False)
    ax2.plot(x, cum.values, color=C_MAND, lw=2.2, label="Cumulative participants")
    ax.axvline(pd.Timestamp("2020-11-16"), color="k", ls="--", lw=1, alpha=0.6)
    ax.text(pd.Timestamp("2020-11-16"), s.max()*0.92, " Pix launch\n 16/11/2020", fontsize=8, va="top")
    ax.set_ylabel("New participants / month"); ax2.set_ylabel("Cumulative participants")
    ax.set_title("Pix participant adoption (first month holding registered keys)")
    l1, lb1 = ax.get_legend_handles_labels(); l2, lb2 = ax2.get_legend_handles_labels()
    ax.legend(l1 + l2, lb1 + lb2, loc="center right", fontsize=8)
    fig.tight_layout(); f = os.path.join(FIG_DIR, "fig1_adoption_curve.png")
    fig.savefig(f); plt.close(fig); return f


def fig_entrants_by_type(entry, tcl):
    m = entry.merge(tcl[["ispb", "mv"]], left_on="ISPB", right_on="ispb", how="left")
    m["mv"] = m["mv"].fillna("Unclassified")
    m["q"] = _anomes_to_period(m["entry_anomes"]).asfreq("Q")
    piv = (m.groupby(["q", "mv"]).size().unstack(fill_value=0))
    order = ["Obrigatória (mandatory)", "Facultativa (voluntary)", "Unclassified"]
    piv = piv.reindex(columns=[c for c in order if c in piv.columns])
    x = piv.index.to_timestamp()
    fig, ax = plt.subplots(figsize=(8, 4.2))
    bottom = np.zeros(len(piv))
    colmap = {order[0]: C_MAND, order[1]: C_FAC, order[2]: C_NA}
    for c in piv.columns:
        ax.bar(x, piv[c].values, bottom=bottom, width=70, color=colmap[c], label=c)
        bottom += piv[c].values
    ax.set_ylabel("New participants"); ax.set_title("New Pix participants per quarter, by participation type")
    ax.legend(fontsize=8)
    fig.tight_layout(); f = os.path.join(FIG_DIR, "fig2_entrants_by_type.png")
    fig.savefig(f); plt.close(fig); return f


def fig_system_keys(panel):
    g = panel.groupby("AnoMes")[["qtd_chaves", "qtd_pf", "qtd_pj"]].sum().sort_index()
    x = _anomes_to_period(pd.Series(g.index)).to_timestamp()
    fig, ax = plt.subplots(figsize=(8, 4.2))
    ax.stackplot(x, g["qtd_pf"].values, g["qtd_pj"].values,
                 labels=["PF (individuals)", "PJ (firms)"], colors=[C_FAC, C_MAND], alpha=0.85)
    ax.yaxis.set_major_formatter(FuncFormatter(_thousands))
    ax.set_ylabel("Registered Pix keys"); ax.set_title("System-wide registered Pix keys over time")
    ax.legend(loc="upper left", fontsize=8)
    fig.tight_layout(); f = os.path.join(FIG_DIR, "fig3_system_keys.png")
    fig.savefig(f); plt.close(fig); return f


def fig_roster_composition(hist):
    h = hist.dropna(subset=["roster_date"]).copy()
    # mandatory/voluntary composition across roster dates (institutions per roster)
    h["mv"] = h["tipo_pix"].map({"obrigatoria": "Obrigatória", "facultativa": "Facultativa"}).fillna("Em adesão / NA")
    piv = h.groupby([h["roster_date"], "mv"])["inst_id"].nunique().unstack(fill_value=0).sort_index()
    for c in ["Obrigatória", "Facultativa", "Em adesão / NA"]:
        if c not in piv.columns: piv[c] = 0
    piv = piv[["Obrigatória", "Facultativa", "Em adesão / NA"]]
    x = piv.index
    fig, ax = plt.subplots(figsize=(8, 4.2))
    ax.stackplot(x, piv["Obrigatória"], piv["Facultativa"], piv["Em adesão / NA"],
                 labels=["Obrigatória (mandatory)", "Facultativa (voluntary)", "Registration / NA"],
                 colors=[C_MAND, C_FAC, C_NA], alpha=0.85)
    ax.set_ylabel("Institutions on roster"); ax.set_title("Roster composition over time: mandatory vs voluntary")
    ax.legend(loc="upper left", fontsize=8)
    fig.tight_layout(); f = os.path.join(FIG_DIR, "fig4_roster_mandatory_voluntary.png")
    fig.savefig(f); plt.close(fig); return f


def fig_direct_indirect(hist):
    h = hist.dropna(subset=["roster_date", "spi"]).copy()
    piv = h.groupby([h["roster_date"], "spi"])["inst_id"].nunique().unstack(fill_value=0).sort_index()
    for c in ["direta", "indireta"]:
        if c not in piv.columns: piv[c] = 0
    x = piv.index
    fig, ax = plt.subplots(figsize=(8, 4.2))
    ax.stackplot(x, piv["direta"], piv["indireta"],
                 labels=["Direta (direct)", "Indireta (indirect)"], colors=[C_DIR, C_IND], alpha=0.85)
    ax.set_ylabel("Institutions on roster"); ax.set_title("SPI participation over time: direct vs indirect settlement")
    ax.legend(loc="upper left", fontsize=8)
    fig.tight_layout(); f = os.path.join(FIG_DIR, "fig5_direct_indirect.png")
    fig.savefig(f); plt.close(fig); return f


def fig_top_holders(panel, tcl):
    last = panel["AnoMes"].max()
    cur = panel[panel["AnoMes"] == last].groupby(["ISPB", "Nome"])["qtd_chaves"].sum().reset_index()
    cur = cur.merge(tcl[["ispb", "mv"]], left_on="ISPB", right_on="ispb", how="left")
    cur["mv"] = cur["mv"].fillna("Unclassified")
    top = cur.sort_values("qtd_chaves", ascending=False).head(15).iloc[::-1]
    colmap = {"Obrigatória (mandatory)": C_MAND, "Facultativa (voluntary)": C_FAC, "Unclassified": C_NA}
    fig, ax = plt.subplots(figsize=(8, 5.0))
    ax.barh(top["Nome"].str.slice(0, 30), top["qtd_chaves"],
            color=[colmap[m] for m in top["mv"]])
    ax.xaxis.set_major_formatter(FuncFormatter(_thousands))
    ax.set_xlabel("Registered keys"); ax.set_title(f"Top 15 institutions by registered Pix keys ({last})")
    from matplotlib.patches import Patch
    ax.legend(handles=[Patch(color=C_MAND, label="Mandatory"), Patch(color=C_FAC, label="Voluntary"),
                       Patch(color=C_NA, label="Unclassified")], fontsize=8, loc="lower right")
    fig.tight_layout(); f = os.path.join(FIG_DIR, "fig6_top_holders.png")
    fig.savefig(f); plt.close(fig); return f, last, cur


# ── TABLES ───────────────────────────────────────────────────────────────────
def tbl_entry_cohort(entry, tcl):
    m = entry.merge(tcl[["ispb", "mv"]], left_on="ISPB", right_on="ispb", how="left")
    m["mv"] = m["mv"].fillna("Unclassified")
    m["year"] = (pd.to_numeric(m["entry_anomes"], errors="coerce") // 100).astype("Int64")
    t = (m.groupby(["year", "mv"]).size().unstack(fill_value=0))
    for c in ["Obrigatória (mandatory)", "Facultativa (voluntary)", "Unclassified"]:
        if c not in t.columns: t[c] = 0
    t = t[["Obrigatória (mandatory)", "Facultativa (voluntary)", "Unclassified"]]
    t["Total"] = t.sum(axis=1)
    t.loc["All years"] = t.sum()
    return t.reset_index().rename(columns={"year": "Entry year"})


def tbl_launch_snapshot(hist):
    h = hist.dropna(subset=["roster_date"])
    with_mv = h[h["tipo_pix"].notna()]
    if with_mv.empty:
        return None, None
    first_date = with_mv["roster_date"].min()
    snap = with_mv[with_mv["roster_date"] == first_date]
    t = (snap.groupby(["tipo_pix", "spi"])["inst_id"].nunique().unstack(fill_value=0))
    t.index = t.index.map({"obrigatoria": "Obrigatória", "facultativa": "Facultativa"})
    t.columns = [c.capitalize() for c in t.columns]
    t["Total"] = t.sum(axis=1); t.loc["Total"] = t.sum()
    return t.reset_index().rename(columns={"index": "Tipo Pix", "tipo_pix": "Tipo Pix"}), first_date.date()


def tbl_top_holders(cur, last):
    tot = cur["qtd_chaves"].sum()
    t = cur.sort_values("qtd_chaves", ascending=False).head(10).copy()
    t["Share %"] = (100 * t["qtd_chaves"] / tot).round(1)
    t["Keys"] = t["qtd_chaves"].map(lambda v: f"{int(v):,}")
    t["Type"] = t["mv"].str.replace(r"\s*\(.*\)", "", regex=True)
    out = t[["Nome", "Keys", "Share %", "Type"]].rename(columns={"Nome": "Institution"})
    out.insert(0, "#", range(1, len(out) + 1))
    return out, last, f"{int(tot):,}"


def tbl_coverage(entry, tcl, hist):
    keys_ispb = set(entry["ISPB"])
    ros_ispb = set(tcl["ispb"].dropna().astype(str).str.replace(r"\.0$", "", regex=True).str.zfill(8))
    both = keys_ispb & ros_ispb
    rows = [
        ("Institutions with key-based entry date (scrape_6)", len(keys_ispb)),
        ("Institutions on ≥1 roster (scrape_7)", hist["inst_id"].nunique()),
        ("Roster institutions matched to an ISPB", len(ros_ispb)),
        ("Matched in BOTH key panel and roster", len(both)),
        ("Key panel only (no roster match)", len(keys_ispb - ros_ispb)),
        ("Classified mandatory/voluntary (ever)", int(tcl["mv"].isin(
            ["Obrigatória (mandatory)", "Facultativa (voluntary)"]).sum())),
    ]
    return pd.DataFrame(rows, columns=["Coverage metric", "Count"])


def build_deposit_classification(tl):
    """Join Pix classification to deposits_panel; aggregate by Year × Quarter × class."""
    list_files = sorted(glob.glob(os.path.join(IF_LIST_DIR, "IF_DATA_List_*.csv")))
    frames = []
    for fp in list_files:
        try:
            df = pd.read_csv(fp, dtype=str,
                             usecols=["CodInst", "CodConglomeradoPrudencial", "CnpjInstituicaoLider"])
            frames.append(df.dropna(subset=["CodConglomeradoPrudencial"]))
        except Exception:
            pass
    iflist = pd.concat(frames, ignore_index=True).drop_duplicates()

    # cnpj8 root → CodConglomeradoPrudencial (primary: leader CNPJ; secondary: CodInst)
    cong_map = {}
    for _, row in iflist.dropna(subset=["CnpjInstituicaoLider"]).iterrows():
        c8 = cnpj8_root(row["CnpjInstituicaoLider"])
        if c8:
            cong_map[c8] = str(row["CodConglomeradoPrudencial"])
    for _, row in iflist.dropna(subset=["CodInst"]).iterrows():
        c8 = cnpj8_root(row["CodInst"])
        if c8 and c8 not in cong_map:
            cong_map[c8] = str(row["CodConglomeradoPrudencial"])

    t = tl.copy()
    t["ispb"] = t["ispb"].astype(str).str.replace(r"\.0$", "", regex=True).str.zfill(8)
    t["cnpj8_r"] = t["cnpj"].apply(cnpj8_root)
    t["cong"] = t["cnpj8_r"].map(cong_map)
    t["ever_mandatory"] = t["ever_mandatory"].astype(str).str.lower().isin(["true", "1"])

    # One row per conglomerate; if conflict keep mandatory
    cong_cls = (t.dropna(subset=["cong"])
                .sort_values("ever_mandatory", ascending=False)
                .drop_duplicates("cong")[["cong", "ever_mandatory"]])
    cong_cls["class"] = cong_cls["ever_mandatory"].map({True: "Mandatory", False: "Voluntary"})

    dep = pd.read_csv(DEPOSITS_CSV, dtype={"CodConglomeradoPrudencial": str})
    dep_cols = [c for c in ["dep_a1", "dep_a2", "dep_a3", "dep_a4", "dep_a5", "dep_outros"]
                if c in dep.columns]
    for c in dep_cols:
        dep[c] = pd.to_numeric(dep[c], errors="coerce")
    dep["dep_total"] = dep[dep_cols].sum(axis=1)

    dep2 = dep.merge(cong_cls[["cong", "class"]],
                     left_on="CodConglomeradoPrudencial", right_on="cong", how="left")
    dep2["class"] = dep2["class"].fillna("Not matched to Pix")

    agg = dep2.groupby(["Year", "Quarter", "class"])["dep_total"].sum().reset_index()
    agg.to_csv(DEPCLASS_CSV, index=False)
    logging.info(f"Saved deposit classification -> {DEPCLASS_CSV} ({len(agg)} rows)")
    n_mand = int(cong_cls["ever_mandatory"].sum())
    n_vol  = int((~cong_cls["ever_mandatory"]).sum())
    return agg, n_mand, n_vol


def build_mandatory_export(tl, hist):
    """Build per-ISPB table for mandatory institutions with time flags."""
    # First roster date per institution with obrigatoria status
    mand_hist = hist[hist["tipo_pix"] == "obrigatoria"].copy()
    first_mand = (mand_hist.groupby("ispb_filled")["roster_date"]
                  .min().reset_index()
                  .rename(columns={"roster_date": "mandatory_since", "ispb_filled": "ispb"}))
    first_mand["ispb"] = first_mand["ispb"].astype(str).str.replace(r"\.0$", "", regex=True).str.zfill(8)

    t = tl.copy()
    t["ispb"] = t["ispb"].astype(str).str.replace(r"\.0$", "", regex=True).str.zfill(8)
    t["ever_mandatory"] = t["ever_mandatory"].astype(str).str.lower().isin(["true", "1"])
    mand = t[t["ever_mandatory"]].copy()

    out = mand.merge(first_mand, on="ispb", how="left")

    def months_diff(row):
        try:
            ms_ts = pd.Timestamp(row["mandatory_since"])
            km_int = int(float(row["entry_month_keys"]))
            km_ts = pd.Timestamp(f"{km_int // 100}-{km_int % 100:02d}-01")
            return (km_ts.year - ms_ts.year) * 12 + (km_ts.month - ms_ts.month)
        except Exception:
            return None

    out["months_to_join"] = out.apply(months_diff, axis=1)

    cols = ["ispb", "nome", "cnpj", "tipo_instituicao",
            "mandatory_since", "entry_month_keys", "months_to_join",
            "first_spi", "last_spi"]
    out = out[[c for c in cols if c in out.columns]].sort_values("mandatory_since")
    out.to_csv(MAND_CSV, index=False)
    logging.info(f"Saved mandatory export -> {MAND_CSV} ({len(out)} rows)")
    return out


def fig_deposits_by_class(depclass):
    df = depclass.copy()
    qmap = {1: "-03", 2: "-06", 3: "-09", 4: "-12"}
    df["period"] = pd.to_datetime(
        df["Year"].astype(str) + df["Quarter"].map(qmap), format="%Y-%m")
    piv = (df.pivot_table(index="period", columns="class", values="dep_total", aggfunc="sum")
           .sort_index().fillna(0))
    for c in ["Mandatory", "Voluntary", "Not matched to Pix"]:
        if c not in piv.columns:
            piv[c] = 0
    piv = piv[["Mandatory", "Voluntary", "Not matched to Pix"]]
    piv_bi = piv / 1e9  # raw R$ → R$ billions

    fig, ax = plt.subplots(figsize=(9, 4.5))
    ax.stackplot(piv_bi.index,
                 piv_bi["Mandatory"], piv_bi["Voluntary"], piv_bi["Not matched to Pix"],
                 labels=["Mandatory", "Voluntary", "Not matched to Pix"],
                 colors=[C_MAND, C_FAC, C_NA], alpha=0.85)
    ax.axvline(pd.Timestamp("2020-11-16"), color="k", ls="--", lw=1, alpha=0.6)
    ymax = piv_bi.sum(axis=1).max()
    ax.text(pd.Timestamp("2020-11-16"), ymax * 0.85, " Pix launch\n 16/11/2020", fontsize=8, va="top")
    ax.set_ylabel("Total deposits (R$ billions)")
    ax.set_title("National deposits by Pix participation class (2013–2024)")
    ax.legend(loc="upper left", fontsize=8)
    ax.yaxis.set_major_formatter(FuncFormatter(lambda x, _: f"{x:,.0f}"))
    fig.tight_layout()
    f = os.path.join(FIG_DIR, "fig7_deposits_by_class.png")
    fig.savefig(f); plt.close(fig); return f


def fig_deposit_share(depclass):
    df = depclass.copy()
    qmap = {1: "-03", 2: "-06", 3: "-09", 4: "-12"}
    df["period"] = pd.to_datetime(
        df["Year"].astype(str) + df["Quarter"].map(qmap), format="%Y-%m")
    piv = (df.pivot_table(index="period", columns="class", values="dep_total", aggfunc="sum")
           .sort_index().fillna(0))
    total = piv.sum(axis=1)
    share = piv.div(total, axis=0) * 100
    for c in ["Mandatory", "Voluntary"]:
        if c not in share.columns:
            share[c] = 0

    fig, ax = plt.subplots(figsize=(9, 4.2))
    ax.plot(share.index, share["Mandatory"], color=C_MAND, lw=2.2, label="Mandatory")
    ax.plot(share.index, share["Voluntary"], color=C_FAC, lw=2.2, label="Voluntary")
    ax.axvline(pd.Timestamp("2020-11-16"), color="k", ls="--", lw=1, alpha=0.6)
    ax.text(pd.Timestamp("2020-11-16"), 5, " Pix launch", fontsize=8, va="bottom")
    ax.set_ylabel("Share of national deposits (%)")
    ax.set_title("Share of national deposits by Pix participation class")
    ax.legend(fontsize=8)
    ax.yaxis.set_major_formatter(FuncFormatter(lambda x, _: f"{x:.0f}%"))
    fig.tight_layout()
    f = os.path.join(FIG_DIR, "fig8_deposit_share.png")
    fig.savefig(f); plt.close(fig); return f


def tbl_mandatory_institutions(mand_df):
    df = mand_df.copy()
    if "mandatory_since" in df.columns:
        df["Mandatory since"] = pd.to_datetime(df["mandatory_since"], errors="coerce").dt.strftime("%Y-%m-%d")
    if "entry_month_keys" in df.columns:
        df["First key month"] = df["entry_month_keys"].apply(
            lambda x: (f"{int(float(x))//100}-{int(float(x))%100:02d}"
                       if pd.notna(x) and str(x) not in ("nan", "") else "—"))
    if "months_to_join" in df.columns:
        df["Months to join"] = df["months_to_join"].apply(
            lambda x: str(int(x)) if pd.notna(x) else "—")
    out = df.rename(columns={"nome": "Institution", "tipo_instituicao": "Type", "first_spi": "SPI mode"})
    display_cols = ["Institution", "Type", "Mandatory since", "First key month", "Months to join", "SPI mode"]
    return out[[c for c in display_cols if c in out.columns]]


def write_section_inplace(section_md: str):
    """Insert/replace the analysis section inside MAIN_MD between marker comments.
    Idempotent: re-running refreshes the block in place — no separate file is left."""
    with open(MAIN_MD, encoding="utf-8") as f:
        doc = f.read()
    block = f"{MARK_START}\n\n{section_md}\n\n{MARK_END}"
    if MARK_START in doc and MARK_END in doc:
        pre  = doc[:doc.index(MARK_START)]
        post = doc[doc.index(MARK_END) + len(MARK_END):]
        doc  = pre + block + post
    else:
        doc = doc.rstrip() + "\n\n---\n\n" + block + "\n"
    with open(MAIN_MD, "w", encoding="utf-8") as f:
        f.write(doc)


def main():
    panel, entry, tl, hist = load()
    tcl = classify(tl)

    f1 = fig_adoption_curve(entry)
    f2 = fig_entrants_by_type(entry, tcl)
    f3 = fig_system_keys(panel)
    f4 = fig_roster_composition(hist)
    f5 = fig_direct_indirect(hist)
    f6, last, cur = fig_top_holders(panel, tcl)

    depclass, n_mand_cong, n_vol_cong = build_deposit_classification(tl)
    mand_df = build_mandatory_export(tl, hist)
    f7 = fig_deposits_by_class(depclass)
    f8 = fig_deposit_share(depclass)

    # Copy all figures alongside the .md file
    for fp in [f1, f2, f3, f4, f5, f6, f7, f8]:
        shutil.copy(fp, os.path.join(DRAFTS, os.path.basename(fp)))
    logging.info(f"Copied all figures to {DRAFTS}")

    t_cohort = tbl_entry_cohort(entry, tcl)
    t_launch, launch_date = tbl_launch_snapshot(hist)
    t_top, last_top, tot_keys = tbl_top_holders(cur, last)
    t_cov = tbl_coverage(entry, tcl, hist)
    t_mand = tbl_mandatory_institutions(mand_df)

    n_part = len(entry)
    rel = lambda p: "pix_timeline_figs/" + os.path.basename(p)
    span = f"{hist['roster_date'].min().date()} – {hist['roster_date'].max().date()}"

    # Deposit snapshot for caption (latest year-quarter in deposits panel)
    yq = depclass[["Year", "Quarter"]].drop_duplicates().sort_values(["Year", "Quarter"])
    yq_latest = yq.iloc[-1]
    snap = depclass[(depclass["Year"] == yq_latest["Year"]) &
                    (depclass["Quarter"] == yq_latest["Quarter"])]
    dep_mand_bi = snap[snap["class"] == "Mandatory"]["dep_total"].sum() / 1e9
    dep_vol_bi  = snap[snap["class"] == "Voluntary"]["dep_total"].sum() / 1e9
    dep_year_q  = f"{int(yq_latest['Year'])}-Q{int(yq_latest['Quarter'])}"
    mand_share  = 100 * dep_mand_bi / (dep_mand_bi + dep_vol_bi) if (dep_mand_bi + dep_vol_bi) > 0 else 0

    md = [
        "## Pix institutional adoption timeline — data analysis",
        (f"*Auto-generated from `pix_participant_*` / `pix_roster_*` (scrape_6 + scrape_7). "
         f"Universe: **{n_part:,} participants**; roster classification spans {span} "
         f"across {hist['roster_date'].nunique()} dated snapshots.*"),
        "### 1. Adoption curve",
        f"![Adoption curve]({rel(f1)})",
        ("The institutional base was essentially set at launch: the registration cohort "
         "(2020-10) dominates, with a long, thin tail of later joiners."),
        "### 2. New entrants by participation type",
        f"![Entrants by type]({rel(f2)})",
        "### 3. System-wide registered keys",
        f"![System keys]({rel(f3)})",
        "### 4. Mandatory vs voluntary composition (roster-based)",
        f"![Mandatory vs voluntary]({rel(f4)})",
        "### 5. Direct vs indirect settlement",
        f"![Direct vs indirect]({rel(f5)})",
        "### 6. Concentration of registered keys",
        f"![Top holders]({rel(f6)})",
        "### 7. National deposits by Pix participation class",
        f"![Deposits by class]({rel(f7)})",
        (f"Mandatory institutions held **R\\${dep_mand_bi:,.0f} billion** in national deposits at "
         f"{dep_year_q}, versus R\\${dep_vol_bi:,.0f} billion for voluntary participants — "
         f"an **{mand_share:.1f}% mandatory share** of Pix-matched deposits. "
         f"({n_mand_cong} mandatory conglomerates vs {n_vol_cong} voluntary matched to the deposits panel.)"),
        "### 8. Mandatory deposit share over time",
        f"![Deposit share]({rel(f8)})",
        "### Tables",
        "**Table 1 — Entry cohort by year × participation type** (key-based entry month).",
        df_to_md(t_cohort),
    ]
    if t_launch is not None:
        md += [
            (f"**Table 2 — First roster carrying the mandatory/voluntary flag "
             f"({launch_date}): mandatory/voluntary × direct/indirect.**"),
            df_to_md(t_launch),
        ]
    md += [
        (f"**Table 3 — Top 10 institutions by registered keys ({last_top}; "
         f"total system keys ≈ {tot_keys}).**"),
        df_to_md(t_top),
        "**Table 4 — Cross-source coverage / reconciliation.**",
        df_to_md(t_cov),
        f"**Table 5 — Mandatory institutions ({len(mand_df)}) with time flags.**",
        df_to_md(t_mand),
    ]

    write_section_inplace("\n\n".join(md))
    logging.info(f"Injected analysis section in place -> {MAIN_MD}")
    logging.info(f"Figures -> {FIG_DIR}")
    print("\n\n".join(md[:2]))
    print(df_to_md(t_cohort))


if __name__ == "__main__":
    main()
