"""
export_comments.py
==================
Master runner for the final LaTeX academic document compilation.

Executes the conversion of localized markdown artifacts and live econometric
estimation output into a formal academic PDF export.  Serves as the final
bridge between the Python analytical engine and the LaTeX distribution.

Pipeline stages
---------------
  Stage 1 - Markdown Parsing
    - Intercepts artifacts (`estimation_summary.md` and `se_comparison.md`).
    - Translates markdown components (bullet points, headers) linearly.

  Stage 2 - LaTeX Safety Filtering
    - Identifies block and inline math boundaries ($ and $$).
    - Escapes critical LaTeX characters (\\&, \\%, \\#, \\_) strictly outside
      of math blocks to prevent `pdflatex` compilation crashes.

  Stage 3 - Estimation Results Embedding
    - Imports estimation_1_sleep as a module to re-run the 12 specifications.
    - Captures cluster homogeneity diagnostics (G, G*, cv) from the live panel.
    - Produces clean booktabs-formatted coefficient tables for each specification.

  Stage 4 - PDF Compilation
    - Wraps all sections in a formal LaTeX document matching model_notes.tex.
    - Exports the intermediate .tex file and drives pdflatex -> biber ->
      pdflatex -> pdflatex compilation via subprocess in Drafts/Deposit Competition.

Usage
-----
  python export_comments.py

Notes
-----
  * If the generated PDF is currently open in any PDF viewer such as Adobe or
    Sumatra, the subprocess will fail with a write-lock error.  Close the PDF
    before running.
  * The script imports estimation_1_sleep directly; ensure market_panel.csv
    has been generated by the data pipeline before running.
"""

import os
import sys
import subprocess
import json
import pickle
try:
    from utils.venv_guard import ensure_project_venv
except Exception:
    ensure_project_venv = None

if ensure_project_venv is not None:
    ensure_project_venv(__file__)

import numpy as np
from pathlib import Path


# ---------------------------------------------------------------------------
# Allow import of sibling module estimation_1_sleep
# ---------------------------------------------------------------------------
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
if _THIS_DIR not in sys.path:
    sys.path.insert(0, _THIS_DIR)

try:
    from utils.toon_parser import load_default_toon_context, load_markdown_artifacts
except Exception:
    load_default_toon_context = None
    load_markdown_artifacts = None


# ==============================================================================
# 1. LaTeX Translation Functions
# ==============================================================================
def md_to_tex_string(md_text):
    """
    Minimalistic markdown-to-LaTeX converter with math safeguards.
    Isolates math regions to prevent erroneous character escaping inside
    display or inline math environments.
    """
    blocks = md_text.split('$$')
    processed_blocks = []

    for i, block in enumerate(blocks):
        if i % 2 == 1:
            # Inside block math — emit as display math unchanged
            processed_blocks.append(f"\\[ {block} \\]")
        else:
            # Outside block math: handle inline math then escape
            inline_parts = block.split('$')
            processed_inline = []
            for j, ipart in enumerate(inline_parts):
                if j % 2 == 1:
                    processed_inline.append(f"${ipart}$")
                else:
                    escaped = (ipart
                               .replace('&', '\\&')
                               .replace('%', '\\%')
                               .replace('#', '\\#')
                               .replace('_', '\\_'))
                    processed_inline.append(escaped)
            processed_blocks.append("".join(processed_inline))

    tex = "".join(processed_blocks)

    lines = tex.split('\n')
    out_lines = []
    in_code = False

    for line in lines:
        if line.startswith('```'):
            if in_code:
                out_lines.append('\\end{lstlisting}')
            else:
                out_lines.append('\\begin{lstlisting}')
            in_code = not in_code
            continue

        if in_code:
            out_lines.append(line)
            continue

        if line.startswith('# '):
            out_lines.append(f"\\section*{{{line[2:]}}}")
        elif line.startswith('## '):
            out_lines.append(f"\\subsection*{{{line[3:]}}}")
        elif line.startswith('### '):
            out_lines.append(f"\\subsubsection*{{{line[4:]}}}")
        elif line.startswith('- '):
            out_lines.append(f"\\textbullet\\ {line[2:]} \\\\")
        elif line.strip() == '':
            out_lines.append("\n\n")
        else:
            out_lines.append(line + " \\\\")

    return '\n'.join(out_lines)


# ==============================================================================
# 2. Booktabs Regression Table Builder
# ==============================================================================
def build_reg_table(res, spec_name, G_nominal, G_star):
    """
    Produces a standalone booktabs LaTeX table from a statsmodels OLS result.

    Parameters
    ----------
    res : statsmodels RegressionResults
    spec_name : str
        Human-readable specification label used as the table caption.
    G_nominal : int
        Nominal number of clusters in this specification.
    G_star : float
        Effective cluster count (Carter et al. 2017).

    Returns
    -------
    str : LaTeX fragment containing the table environment.
    """
    params    = res.params
    bse       = res.bse
    tvalues   = res.tvalues
    pvalues   = res.pvalues
    conf      = res.conf_int()
    nobs      = int(res.nobs)
    rsq       = res.rsquared

    def stars(p):
        if p < 0.01:
            return '***'
        elif p < 0.05:
            return '**'
        elif p < 0.10:
            return '*'
        return ''

    # Variable name prettifier
    def pretty(name):
        name = name.replace('_', '\\_').replace('interaction\\_', '')
        return name

    rows = []
    for var in params.index:
        coef = params[var]
        se   = bse[var]
        p    = pvalues[var]
        s    = stars(p)
        rows.append(
            f"    {pretty(var)} & ${coef:.4f}^{{{s}}}$ & $({se:.4f})$ & ${p:.3f}$ \\\\"
        )

    body = '\n'.join(rows)

    table = (
        f"\\begin{{table}}[htbp]\n"
        f"\\centering\n"
        f"\\caption{{{spec_name}}}\n"
        f"\\label{{tab:{spec_name.replace(' ', '_').replace('/', '').replace(':', '')}}}\n"
        f"\\begin{{tabular}}{{lccc}}\n"
        f"\\toprule\n"
        f"Variable & Coefficient & (Std.\\ Error) & $p$-value \\\\\n"
        f"\\midrule\n"
        f"{body}\n"
        f"\\midrule\n"
        f"\\multicolumn{{4}}{{l}}{{\\footnotesize Obs: {nobs:,} "
        f"\\quad $G = {G_nominal}$ "
        f"\\quad $G^* = {G_star:.2f}$ "
        f"\\quad $R^2 = {rsq:.4f}$}} \\\\\n"
        f"\\multicolumn{{4}}{{l}}{{\\footnotesize "
        f"SEs clustered by prudential conglomerate. "
        f"Inference based on $t_{{G^*}}$ (\\textcite{{imbens2016robust}}; "
        f"\\textcite{{carter2017asymptotic}}).}} \\\\\n"
        f"\\bottomrule\n"
        f"\\end{{tabular}}\n"
        f"\\end{{table}}\n"
    )
    return table


# ==============================================================================
# 3. Cluster Diagnostics LaTeX Block Builder
# ==============================================================================
def build_cluster_diagnostics_tex(df):
    """
    Computes cluster imbalance statistics and returns a formatted LaTeX block
    containing a summary table of the diagnostics.

    Parameters
    ----------
    df : pandas DataFrame
        The estimation-ready panel (output of estimation_1_sleep.build_data).

    Returns
    -------
    str : LaTeX fragment.
    """
    cluster_var = 'CodConglomeradoPrudencial'
    Ns       = df.groupby(cluster_var).size()
    G        = len(Ns)
    mean_Ng  = float(np.mean(Ns))
    std_Ng   = float(np.std(Ns, ddof=0))
    cv       = std_Ng / mean_Ng if mean_Ng > 0 else 0
    G_star   = max(1.0, G / (1 + cv ** 2))
    total    = len(df)

    top5 = Ns.sort_values(ascending=False).head(5)
    top5_rows = '\n'.join(
        f"    {c} & {n:,} & {(n / total) * 100:.1f}\\% \\\\"
        for c, n in top5.items()
    )

    block = (
        "\\subsection*{Cluster Homogeneity Diagnostics "
        "(\\textcite{carter2017asymptotic}; \\textcite{imbens2016robust})}\n\n"
        "The effective number of clusters $G^*$ collapses the nominal group "
        "count by the degree of cluster-size imbalance:\n"
        "\\[ G^* = \\frac{G}{1 + \\mathrm{cv}^2} \\]\n\n"
        "\\begin{table}[htbp]\n"
        "\\centering\n"
        "\\caption{Cluster Homogeneity Summary}\n"
        "\\label{tab:cluster_diag}\n"
        "\\begin{tabular}{lc}\n"
        "\\toprule\n"
        "Statistic & Value \\\\\n"
        "\\midrule\n"
        f"Nominal clusters ($G$) & {G} \\\\\n"
        f"Mean obs.\\ per cluster ($\\bar{{N}}_g$) & {mean_Ng:,.1f} \\\\\n"
        f"Std.\\ dev.\\ of cluster size ($\\sigma_{{N_g}}$) & {std_Ng:,.1f} \\\\\n"
        f"Coefficient of variation ($\\mathrm{{cv}}$) & {cv:.3f} \\\\\n"
        f"Effective clusters ($G^*$) & {G_star:.2f} \\\\\n"
        f"Total observations & {total:,} \\\\\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
        "\\end{table}\n\n"
        "\\begin{table}[htbp]\n"
        "\\centering\n"
        "\\caption{Top-5 Conglomerates by Observation Share}\n"
        "\\label{tab:top5_clusters}\n"
        "\\begin{tabular}{lcc}\n"
        "\\toprule\n"
        "Conglomerate & Observations & Share \\\\\n"
        "\\midrule\n"
        f"{top5_rows}\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
        "\\end{table}\n\n"
        f"Because $G^* \\approx {G_star:.2f} < 10$, standard cluster-robust "
        "variance estimators (CR1) and Wild Cluster Bootstrap inference "
        "systematically over-reject. All inference below is conducted using "
        "a $t$-distribution with $df = G^*$ following "
        "\\textcite{imbens2016robust} and \\textcite{carter2017asymptotic}. \\\\\n"
    )
    return block, G, G_star


# ==============================================================================
# 4. Global Execution Routine
# ==============================================================================
def main():
    print(f"\n=====================================================================")
    print(" INITIATING PDFLATEX COMPILATION PIPELINE")
    print("=====================================================================")

    # --------------------------------------------------------------------------
    # 4a. Load markdown artifacts (methodology sections)
    # --------------------------------------------------------------------------
    default_brain_dir = (
        r"C:\Users\pedro\.gemini\antigravity\brain\13d50388-cbdf-4a6d-bc55-492e6d1a04f0"
    )

    print(" - Loading markdown artifacts...")
    toon_context = {}
    if load_default_toon_context is not None:
        try:
            toon_context = load_default_toon_context(Path(_THIS_DIR) / "utils", quiet=True)
        except Exception:
            toon_context = {}

    if load_markdown_artifacts is not None:
        summary_text, se_text, md_meta = load_markdown_artifacts(
            toon_context,
            default_brain_dir=default_brain_dir,
        )
        summary_md = md_meta["summary_path"]
        se_md = md_meta["se_path"]
    else:
        brain_dir = default_brain_dir
        summary_md = os.path.join(brain_dir, 'estimation_summary.md')
        se_md = os.path.join(brain_dir, 'se_comparison.md')
        with open(summary_md, 'r', encoding='utf-8') as f:
            summary_text = f.read()
        with open(se_md, 'r', encoding='utf-8') as f:
            se_text = f.read()

    if not summary_text.strip() or not se_text.strip():
        raise FileNotFoundError(
            "Markdown artifacts are empty or missing. "
            f"Resolved files: {summary_md} | {se_md}"
        )

    print(" - Translating markdown to LaTeX...")
    tex_body_md = (md_to_tex_string(summary_text)
                   + "\n\n\\newpage\n"
                   + md_to_tex_string(se_text))

    # --------------------------------------------------------------------------
    # 4b. Load or run estimation
    # --------------------------------------------------------------------------
    import estimation_1_sleep as est
    import pickle
    import json
    
    # Check if saved results exist
    panel_csv, output_dir = est._resolve_runtime_paths()
    results_pickle = Path(output_dir) / "estimation_results.pkl"
    cluster_diag_json = Path(output_dir) / "cluster_diagnostics.json"
    
    if results_pickle.exists() and cluster_diag_json.exists():
        print(" - Loading saved estimation results (pickle+JSON)...")
        with open(results_pickle, 'rb') as f:
            results_dict = pickle.load(f)
        with open(cluster_diag_json, 'r') as f:
            cluster_diag_data = json.load(f)
        
        # Convert results_dict to ordered list matching export format
        results_ordered = [(spec_name, res) for spec_name, res in results_dict.items()]
        G_nominal_global = cluster_diag_data['G_nominal']
        G_star_global = cluster_diag_data['G_star']
        print(f"   Loaded {len(results_ordered)} specifications from cache")
        print(f"   Cluster diagnostics: G={G_nominal_global}, G*={G_star_global:.2f}")
    else:
        print(" - Saved results not found; running estimation...")
        import concurrent.futures
        
        df = est.build_data()
        print(f"   Panel ready: {len(df):,} rows")

        # Compute cluster diagnostics
        print(" - Computing cluster diagnostics...")
        diag_tex_dummy, G_nominal_global, G_star_global = build_cluster_diagnostics_tex(df)

        # Run all 12 specifications
        print(" - Running 12 specifications (parallel)...")

        df['constant'] = 1.0
        s_base        = ['constant']
        s_macro       = s_base + ['gdp_per_capita', 'cadunico_families_per1000',
                                   'fraction_65plus', 'fraction_young']
        s_tech        = s_macro + ['pix_users_pf_per1000', 'connections_per100',
                                   'branches_per1000']

        for col in s_tech:
            if col != 'constant' and col in df.columns:
                df[col] = df[col].fillna(df[col].median())

        iv_spec0 = []
        iv_spec1 = ['personnel_cost_ratio_lag', 'admin_cost_ratio_lag', 'tax_cost_ratio_lag']
        iv_spec2 = iv_spec1 + ['lci_lca_ratio_lag', 'wholesale_ratio_lag', 'indice_basileia_lag']
        iv_spec3 = iv_spec2 + ['leave_one_out_mean_spread']

        specs = [
            ('Spec1-OLS',             iv_spec0),
            ('Spec2-IV_CostShifters', iv_spec1),
            ('Spec3-IV_Wholesale',    iv_spec2),
            ('Spec4-IV_HausmanFull',  iv_spec3),
        ]
        state_blocks = [
            ('Base',  s_base),
            ('Macro', s_macro),
            ('Tech',  s_tech),
        ]

        tasks = [
            (df, iv_name, iv_cols, s_name, s_cols)
            for iv_name, iv_cols in specs
            for s_name, s_cols in state_blocks
        ]

        results_ordered = []
        with concurrent.futures.ProcessPoolExecutor() as executor:
            for stdout_text, res, spec_name in executor.map(est.execute_specification, tasks):
                print(stdout_text, end='')
                results_ordered.append((spec_name, res))

    # Build cluster diagnostics LaTeX block from saved data
    if 'cluster_diag_data' in locals():
        diag = cluster_diag_data
        top5_rows = '\n'.join(
            f"    {c} & {data['observations']:,} & {data['share_pct']:.1f}\\% \\\\"
            for c, data in diag['top_5_clusters'].items()
        )
        diag_tex = (
            "\\subsection*{Cluster Homogeneity Diagnostics "
            "(\\textcite{carter2017asymptotic}; \\textcite{imbens2016robust})}\n\n"
            "The effective number of clusters $G^*$ collapses the nominal group "
            "count by the degree of cluster-size imbalance:\n"
            "\\[ G^* = \\frac{G}{1 + \\mathrm{cv}^2} \\]\n\n"
            "\\begin{table}[htbp]\n"
            "\\centering\n"
            "\\caption{Cluster Homogeneity Summary}\n"
            "\\label{tab:cluster_diag}\n"
            "\\begin{tabular}{lc}\n"
            "\\toprule\n"
            "Statistic & Value \\\\\n"
            "\\midrule\n"
            f"Nominal clusters ($G$) & {diag['G_nominal']} \\\\\n"
            f"Mean obs.\\ per cluster ($\\bar{{N}}_g$) & {diag['mean_obs_per_cluster']:,.1f} \\\\\n"
            f"Std.\\ dev.\\ of cluster size ($\\sigma_{{N_g}}$) & {diag['std_obs_per_cluster']:,.1f} \\\\\n"
            f"Coefficient of variation ($\\mathrm{{cv}}$) & {diag['coefficient_variation']:.3f} \\\\\n"
            f"Effective clusters ($G^*$) & {diag['G_star']:.2f} \\\\\n"
            f"Total observations & {diag['total_observations']:,} \\\\\n"
            "\\bottomrule\n"
            "\\end{tabular}\n"
            "\\end{table}\n\n"
            "\\begin{table}[htbp]\n"
            "\\centering\n"
            "\\caption{Top-5 Conglomerates by Observation Share}\n"
            "\\label{tab:top5_clusters}\n"
            "\\begin{tabular}{lcc}\n"
            "\\toprule\n"
            "Conglomerate & Observations & Share \\\\\n"
            "\\midrule\n"
            f"{top5_rows}\n"
            "\\bottomrule\n"
            "\\end{tabular}\n"
            "\\end{table}\n\n"
            f"Because $G^* \\approx {diag['G_star']:.2f} < 10$, standard cluster-robust "
            "variance estimators (CR1) and Wild Cluster Bootstrap inference "
            "systematically over-reject. All inference below is conducted using "
            "a $t$-distribution with $df = G^*$ following "
            "\\textcite{imbens2016robust} and \\textcite{carter2017asymptotic}. \\\\\n"
        )
    else:
        # Fallback: compute from data (for backward compatibility)
        diag_tex, G_nominal_global, G_star_global = build_cluster_diagnostics_tex(df)
    
    print(" - Building regression table blocks...")
    tables_tex = "\\newpage\n\\section*{Estimation Results}\n\n"
    tables_tex += ("All specifications estimate the depositor sleepiness "
                   "function \\parencite{imbens2016robust,carter2017asymptotic}. "
                   "Stars denote significance: *** $p<0.01$, ** $p<0.05$, * $p<0.10$. "
                   "Standard errors are clustered at the conglomerate level; "
                   "inference uses $t_{G^*}$ degrees of freedom.\n\n")

    for spec_name, res in results_ordered:
        if res is not None:
            # Recover G* per spec (recompute from the result nobs; approximate)
            tables_tex += build_reg_table(res, spec_name, G_nominal_global, G_star_global)
            tables_tex += "\n\n"
        else:
            tables_tex += (f"\\paragraph{{{spec_name}}} Specification could not be "
                           f"estimated (insufficient data or collinear instruments).\n\n")

    # --------------------------------------------------------------------------
    # 4f. Assemble final LaTeX document
    # --------------------------------------------------------------------------
    print(" - Assembling final LaTeX document...")

    preamble = r"""% Estimation_Summary_and_SE.tex
% Generated by export_comments.py
% Open Finance --- Deposit Competition Estimation Results
% Author: Pedro Feijo de Moraes
% Date: March 2026
% Compile: pdflatex Estimation_Summary_and_SE.tex && biber Estimation_Summary_and_SE && pdflatex Estimation_Summary_and_SE.tex && pdflatex Estimation_Summary_and_SE.tex

\documentclass[11pt,letterpaper]{article}

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}
\usepackage{lmodern}
\usepackage[top=2.8cm,bottom=2.8cm,left=1.0cm,right=1.0cm]{geometry}
\usepackage{amsmath,amssymb,amsthm}
\usepackage{booktabs}
\usepackage{array}
\usepackage{longtable}
\usepackage{tabularx}
\usepackage{xltabular}
\usepackage{xurl}
\usepackage[dvipsnames]{xcolor}
\usepackage{hyperref}
\usepackage{enumitem}
\usepackage{parskip}
\usepackage{microtype}
\usepackage{csquotes}
\usepackage{etoolbox}
\usepackage{fancyhdr}
\usepackage{titlesec}
\usepackage{listings}
\usepackage[font=small,labelfont=bf]{caption}
\usepackage[backend=biber, style=authoryear, maxcitenames=2, sortcites=true, sorting=ynt]{biblatex}
\DeclareDelimFormat[bib,textcite,parencite]{finalnamedelim}{\addspace\&\addspace}
\DeclareDelimFormat[bib,parencite]{nameyeardelim}{\addcomma\space}
\DeclareDelimFormat[textcite]{nameyeardelim}{\addspace}
\addbibresource{../References.bib}

\definecolor{yalegray}{RGB}{90,90,90}
\definecolor{yaleblue}{RGB}{0,53,107}
\definecolor{codebg}{RGB}{248,248,248}
\definecolor{codeframe}{RGB}{180,180,180}

\hypersetup{colorlinks=true, linkcolor=RoyalBlue, urlcolor=RoyalBlue, citecolor=RoyalBlue}
\urlstyle{tt}

\setlength{\tabcolsep}{3.5pt}
\renewcommand{\arraystretch}{1.08}
\setlength{\emergencystretch}{2em}
\AtBeginEnvironment{xltabular}{\footnotesize}
\AtBeginEnvironment{tabularx}{\footnotesize}
\AtBeginEnvironment{longtable}{\footnotesize}

\pagestyle{fancy}
\fancyhf{}
\rhead{\small\color{yalegray}Estimation Summary --- Deposit Competition}
\lhead{\small\color{yalegray}Feijo de Moraes (2026)}
\rfoot{\small\thepage}
\renewcommand{\headrulewidth}{0.3pt}

\titleformat{\section}{\large\bfseries\color{yaleblue}}{}{0em}{}[\titlerule]
\titleformat{\subsection}{\normalsize\bfseries}{}{0em}{}

\lstset{
	basicstyle=\ttfamily\small,
	backgroundcolor=\color{codebg},
	frame=single,
	rulecolor=\color{codeframe},
	breaklines=true,
	columns=flexible,
	keepspaces=true,
	showstringspaces=false,
	language=bash,
}

\newcolumntype{L}[1]{>{\raggedright\arraybackslash}p{#1}}
\newcommand{\breakcode}[1]{\begingroup\urlstyle{tt}\nolinkurl{#1}\endgroup}
\newcolumntype{Y}{>{\raggedright\arraybackslash}X}

\newcommand{\E}{\mathbb{E}}
\newcommand{\N}{\mathcal{N}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\bx}{\mathbf{x}}
\newcommand{\bX}{\mathbf{X}}
\newcommand{\bz}{\mathbf{z}}
\newcommand{\bs}{\mathbf{s}}
\newcommand{\bS}{\mathbf{S}}
\newcommand{\blambda}{\boldsymbol{\lambda}}
\newcommand{\btheta}{\boldsymbol{\theta}}
\newcommand{\bSigma}{\boldsymbol{\Sigma}}
\newcommand{\bPi}{\boldsymbol{\Pi}}
\newcommand{\bnu}{\boldsymbol{\nu}}
\newcommand{\bxi}{\boldsymbol{\xi}}
\newcommand{\bfrac}[2]{\dfrac{#1}{#2}}

\theoremstyle{remark}
\newtheorem*{remark}{Remark}
"""

    tex_doc = (
        preamble
        + "\n\\begin{document}\n\n"
        + tex_body_md
        + "\n\n\\newpage\n\\section*{Cluster Homogeneity Diagnostics}\n\n"
        + diag_tex
        + "\n\n"
        + tables_tex
        + "\n\n\\newpage\n\\printbibliography\n\\end{document}\n"
    )

    out_dir  = (r"c:\Users\pedro\OneDrive\Documentos\Yale"
                r"\Year 3 (2024 - 2025)\Open Finance\Open-Finance"
                r"\Drafts\Deposit Competition")
    os.makedirs(out_dir, exist_ok=True)
    temp_tex = os.path.join(out_dir, "Estimation_Summary_and_SE.tex")

    print(f" - Writing .tex file to: {temp_tex}...")
    with open(temp_tex, 'w', encoding='utf-8') as f:
        f.write(tex_doc)

    # --------------------------------------------------------------------------
    # 4g. Compile: pdflatex -> biber -> pdflatex -> pdflatex
    # --------------------------------------------------------------------------
    print(" - Compiling (pdflatex + biber + pdflatex x2). Ensure PDF viewer is closed...")
    try:
        subprocess.run(["pdflatex", "-interaction=nonstopmode", temp_tex],
                       cwd=out_dir, capture_output=True, text=True)
        subprocess.run(["biber", "Estimation_Summary_and_SE"],
                       cwd=out_dir, capture_output=True, text=True)
        subprocess.run(["pdflatex", "-interaction=nonstopmode", temp_tex],
                       cwd=out_dir, capture_output=True, text=True)
        res_final = subprocess.run(["pdflatex", "-interaction=nonstopmode", temp_tex],
                                   cwd=out_dir, capture_output=True, text=True)

        pdf_path = os.path.join(out_dir, "Estimation_Summary_and_SE.pdf")
        if os.path.exists(pdf_path) and os.path.getsize(pdf_path) > 0:
            print("\n *** PDF SUCCESSFULLY GENERATED. ***\n")
        else:
            print(f"\n *** PDF GENERATION FAILED. Log tail:\n"
                  f"{res_final.stdout[-800:]}\n ***\n")
    except Exception as e:
        print(f"\n *** FATAL SYSTEM ERROR: {e} ***\n")

    print("=====================================================================\n")


if __name__ == "__main__":
    main()
