"""
make_cf1_franchise_table.py
=======================
Generator for the CF1 (franchise value — sleepiness decomposition) LaTeX table.
Reads the per-observation decomposition parquet written by cf1_franchise.jl
(model-based) OR diag_cf1_franchise_dataonly.py (data-only), aggregates to firm-type and
deposit-type, and writes a booktabs table into the drafts folder.

⚠ Per project rule: NEVER hand-edit the generated .tex (or V_Main.tex). Edit THIS
generator and re-run. The table is \\input-ed by the paper, not pasted.

Inputs (auto-detected; pass --in to override):
  processed/ESTIMATION_OUTPUT/CF_FOUNDATION/cf1_franchise_gross_E{e}_spec_{s}_{stage}{suffix}.parquet
  processed/ESTIMATION_OUTPUT/CF_FOUNDATION/cf1_franchise_dataonly_E{e}_spec_{s}{suffix}.parquet
Columns expected: is_B (bool), deposit_type (int), V_phi, V_0, dV_sleep.

Output:
  Drafts/Deposit Competition/tab_cf1_franchise{suffix}.tex   (table fragment, \\input-able)
  (--pdf also compiles a standalone preview PDF via pdflatex.)

Usage:
  python make_cf1_franchise_table.py --estim 6 --spec 12 --stage extended
  python make_cf1_franchise_table.py --in <path-to-parquet> --pdf
"""
from utils.venv_guard import ensure_project_venv
ensure_project_venv(__file__)

import argparse
import subprocess
from pathlib import Path

import numpy as np
import pandas as pd

_ROOT = Path(__file__).resolve().parents[2]
CF_DIR = _ROOT / "BCB" / "Egan_et_al_2025_Rep" / "processed" / "ESTIMATION_OUTPUT" / "CF_FOUNDATION"
DRAFTS = _ROOT / "Drafts" / "Deposit Competition"

K_LABEL = {1: "Demand", 2: "Savings", 4: "Time/CDB", 5: "Prepaid"}


def _resolve_input(args) -> Path:
    if args.__dict__.get("in"):
        return Path(args.__dict__["in"])
    tag = f"E{args.estim}_spec_{args.spec}_{args.stage}{args.suffix}"
    # --kind picks the variant explicitly. cf1_franchise.jl writes gross AND net
    # (net subtracts the BBL marginal cost); they are different economic objects, so asking
    # for one and silently getting the other would misreport the table.
    named = {
        "gross":    CF_DIR / f"cf1_franchise_gross_{tag}.parquet",
        "net":      CF_DIR / f"cf1_franchise_net_{tag}.parquet",
        "dataonly": CF_DIR / f"cf1_franchise_dataonly_E{args.estim}_spec_{args.spec}{args.suffix}.parquet",
    }
    kind = getattr(args, "kind", "gross")
    if kind != "auto":
        c = named[kind]
        if c.exists():
            return c
        raise FileNotFoundError(f"No CF1 '{kind}' parquet at {c}")
    cands = [named["gross"], named["dataonly"]]
    for c in cands:
        if c.exists():
            return c
    raise FileNotFoundError(f"No CF1 parquet found. Tried:\n  " + "\n  ".join(map(str, cands)))


def _row(label: str, d: pd.DataFrame) -> str:
    vphi = d["V_phi"].sum()
    v0 = d["V_0"].sum()
    dv = d["dV_sleep"].sum()
    share = 100.0 * dv / vphi if abs(vphi) > 0 else np.nan
    # Scale to billions for readability (values are R$ thousands → /1e9 ≈ R$ bn).
    f = lambda x: f"{x/1e9:,.2f}"
    return f"{label} & {f(vphi)} & {f(v0)} & {f(dv)} & {share:.1f}\\% \\\\"


_CAPTION_KIND = {"gross": "model-based, gross of cost",
                 "net": "model-based, net of cost"}


def build_table(df: pd.DataFrame, src_kind: str) -> str:
    lines = [
        "% AUTO-GENERATED by make_cf1_franchise_table.py — do not edit by hand.",
        "\\begin{table}[htbp]\\centering",
        "\\caption{Franchise value attributable to depositor sleepiness "
        f"({_CAPTION_KIND.get(src_kind, 'data-only, descriptive')}).}}",
        "\\label{tab:cf1_franchise}",
        "\\small",
        "\\begin{tabular}{lrrrr}\\toprule",
        " & $V(\\hat\\phi)$ & $V(\\phi{=}0)$ & $\\Delta V^{\\mathrm{sleep}}$ "
        "& \\% from inertia \\\\",
        "\\midrule",
        _row("\\textbf{All}", df),
        "\\addlinespace",
        "\\multicolumn{5}{l}{\\textit{By firm type}} \\\\",
    ]
    if df["is_B"].any():
        lines.append(_row("\\quad B (brick-and-mortar)", df[df["is_B"]]))
    if (~df["is_B"]).any():
        lines.append(_row("\\quad D (digital/national)", df[~df["is_B"]]))
    lines += ["\\addlinespace", "\\multicolumn{5}{l}{\\textit{By deposit type}} \\\\"]
    for k in sorted(df["deposit_type"].unique()):
        lines.append(_row(f"\\quad $k={k}$ ({K_LABEL.get(int(k), str(k))})",
                          df[df["deposit_type"] == k]))
    lines += [
        "\\bottomrule",
        "\\multicolumn{5}{p{0.92\\textwidth}}{\\scriptsize \\textit{Notes:} "
        "Discounted deposit-funding value (R\\$ bn) over a "
        "50-quarter horizon at $\\beta{=}0.9$. $V(\\hat\\phi)$ uses the estimated "
        "sleeper share; $V(\\phi{=}0)$ removes depositor inertia (active demand only). "
        "$\\Delta V^{\\mathrm{sleep}}$ is the franchise value created by inertia. "
        + ("Gross of marginal cost (deposit-funding markdown only); see the net-of-cost "
           "variant for the margin after BBL marginal costs." if src_kind == "gross"
           else "Net of the BBL-estimated marginal cost: the margin the franchise actually "
                "earns, rather than the funding markdown alone." if src_kind == "net"
           else "Descriptive: uses observed deposits and data-implied active deposits "
                "$\\widehat{\\mathrm{Dep}}^{\\mathrm{Act}}$, not the re-solved demand model.")
        + "} \\\\",
        "\\end{tabular}",
        "\\end{table}",
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--estim", type=int, default=6)
    ap.add_argument("--spec", type=int, default=12)
    ap.add_argument("--stage", type=str, default="extended")
    ap.add_argument("--suffix", type=str, default="")
    ap.add_argument("--in", type=str, default=None, help="explicit input parquet")
    ap.add_argument("--kind", choices=["gross", "net", "dataonly", "auto"],
                    default="gross", help="which CF1 variant to tabulate")
    ap.add_argument("--pdf", action="store_true", help="also compile a preview PDF")
    args = ap.parse_args()

    src = _resolve_input(args)
    src_kind = ("net" if "_net_" in src.name else
                "gross" if "gross" in src.name else "dataonly")
    df = pd.read_parquet(src)
    for c in ("is_B", "deposit_type", "V_phi", "V_0", "dV_sleep"):
        if c not in df.columns:
            raise ValueError(f"Input {src.name} missing column '{c}'")
    print(f"  Loaded {len(df):,} rows from {src.name} ({src_kind})")

    tex = build_table(df, src_kind)
    DRAFTS.mkdir(parents=True, exist_ok=True)
    # Routine and variant go in the NAME. One shared filename means running the exporter
    # per routine leaves whichever ran last sitting in the paper, silently.
    out_tex = DRAFTS / f"tab_cf1_franchise_E{args.estim}_{src_kind}{args.suffix}.tex"
    out_tex.write_text(tex, encoding="utf-8")
    print(f"  Wrote table fragment → {out_tex.name}")

    if args.pdf:
        wrapper = (
            "\\documentclass[11pt]{article}\\usepackage{booktabs,amsmath,geometry}"
            "\\geometry{margin=1in}\\begin{document}\n"
            f"\\input{{{out_tex.stem}}}\n\\end{{document}}\n")
        prev = DRAFTS / f"tab_cf1_franchise_E{args.estim}_{src_kind}{args.suffix}_preview.tex"
        prev.write_text(wrapper, encoding="utf-8")
        try:
            for _ in range(2):
                subprocess.run(["pdflatex", "-interaction=nonstopmode", prev.name],
                               cwd=str(DRAFTS), capture_output=True, text=True)
            print(f"  Compiled preview → {prev.with_suffix('.pdf').name}")
        except FileNotFoundError:
            print("  [WARN] pdflatex not found; wrote .tex only.")


if __name__ == "__main__":
    main()
