#!/usr/bin/env python3
"""
make_polfunc_md_table.py
========================
Regenerate a policy-function results section of `counterfactuals_plan.md` from the
BBL Step-1 estimation summary JSON. Reproducible counterpart of the paper fragments
`polfunc_k{4,5}.tex` / `polfunc_rate_k{4,5}.tex` (written by
bbl_polfunc.py). Reads the CURRENT .md, replaces the block between
sentinels, and writes the WHOLE .md back (narrative untouched).

Two variants, keyed by --depvar (matching the estimator's --depvar):
    spread : §2.6, LHS = compounded annual deposit spread (1+r^f)^4-(1+r^dep)^4 (the policy fed
             to Step 2), k=4 in percentage points and k=5 in basis points   [default]
    rate   : §2.7, LHS = annualized deposit rate (1+rate_qoq)^4-1

    python make_polfunc_md_table.py                  # spread
    python make_polfunc_md_table.py --depvar rate    # deposit rate

The policy function is SPEC-INVARIANT, so neither the estimator nor these outputs carry a
sleepiness-spec label.
"""
import argparse
import json
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]           # .../Open-Finance
SUMMARY_DIR = _ROOT / "BCB" / "Egan_et_al_2025_Rep" / "processed" / "ESTIMATION_OUTPUT" / "COST_POLFUNC"
MD_PATH = _ROOT / "Drafts" / "Deposit Competition" / "counterfactuals_plan.md"
ANCHOR = "## 3. The execution plan (easiest → hardest)"   # §2.6/§2.7 are inserted just before §3

# Display units and the segment-dummy list are IMPORTED from the estimator, not duplicated, so the
# .md and the .tex fragments can never drift apart. Units are pinned to the sleepiness/demand tables
# (see the _DISPLAY_UNITS comment in bbl_polfunc.py).
from bbl_polfunc import (_DISPLAY_UNITS, _SEGMENT_VARS, CFG as _CFG_SPREAD, _CFG_RATE,
                         _lhs_display, _lhs_unit_name)
import sys

# Windows consoles default to cp1252 and raise UnicodeEncodeError on any non-ASCII
# character in a print (phi, arrows, Upsilon, x). That usually fires on a STATUS line after
# the real work is done, so the script exits non-zero and reports failure for a computation
# that succeeded -- three such false failures on 2026-07-29. Force UTF-8 (no-op if already).
try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

K_LABELS = {4: "Time_CDB", 5: "Prepaid"}
K_TITLES = {4: "Panel A: Time deposits / CDB (k=4)", 5: "Panel B: Prepaid accounts (k=5)"}
# Pooled (Option C) is estimated but NOT displayed: Step 2 uses only B and D_optB, and pooling
# few-but-huge B clusters with many-small D ones collapses the effective cluster count.
COLS = ["B", "D_optA", "D_optB"]
COL_HEADERS = ["B-type", "D (no demo.)", "D (natl. demo.)"]

DEMO_BASES = ["gdp_per_capita", "fraction_65plus", "fraction_young",
              "pix_users_pf_per1000", "connections_per100", "branches_per1000",
              "cadunico_families_per1000"]

LABELS = {
    "const": "Constant",
    "log_total_assets_lag": "Log total assets (t−1)",
    "equity_ratio_lag": "Equity ratio (t−1)",
    "has_ip": "Group Contains IP",
    "asset_return_qoq_lag": "Asset return (QoQ, t−1)",
    "npl_provision_ratio_lag": "NPL provisions ratio (t−1)",
    "credit_assets_lag": "Credit / assets (t−1)",
    "seg_S2": "Segment S2", "seg_S3": "Segment S3", "seg_S4": "Segment S4", "seg_S5": "Segment S5",
    "personnel_cost_ratio_lag": "Personnel cost ratio (t−1)",
    "admin_cost_ratio_lag": "Admin cost ratio (t−1)",
    "tax_cost_ratio_lag": "Tax cost ratio (t−1)",
    "indice_basileia_lag": "Basel index (t−1)",
    "wholesale_ratio_lag": "Wholesale ratio (t−1)",
    "lci_lca_ratio_lag": "LCI/LCA ratio (t−1)",
    "risk_free_qoq": "Risk-free rate (QoQ)",
    "log_total_assets_lag_sq": "Log total assets²",
    "equity_ratio_lag_sq": "Equity ratio²",
    "risk_free_qoq_sq": "Risk-free rate²",
    "gdp_per_capita": "GDP per capita",
    "fraction_65plus": "Fraction 65+",
    "fraction_young": "Fraction young",
    "pix_users_pf_per1000": "Pix users",
    "connections_per100": "Mobile lines",
    "branches_per1000": "Branches",
    "cadunico_families_per1000": "CadUnico families",
}

# Per-variant configuration.
VARIANTS = {
    "spread": {
        "summary_prefix": "polfunc",
        "start": "<!-- POLFUNC-SECTION:START (generated by make_polfunc_md_table.py — regenerate, do not hand-edit) -->",
        "end": "<!-- POLFUNC-SECTION:END -->",
        "heading": "### 2.6 The estimated policy function — spread",
        "tex_pattern": "polfunc_k{k}.tex",
        "tab_base": "tab:polfunc",
    },
    "rate": {
        "summary_prefix": "polfunc_rate",
        "start": "<!-- POLFUNC-RATE-SECTION:START (generated by make_polfunc_md_table.py --depvar rate — regenerate, do not hand-edit) -->",
        "end": "<!-- POLFUNC-RATE-SECTION:END -->",
        "heading": "### 2.7 The estimated policy function — deposit rate",
        "tex_pattern": "polfunc_rate_k{k}.tex",
        "tab_base": "tab:polfunc_rate",
    },
}


# Three decimals on every number, never -0.000, as in the .tex fragments (V_Main display rule,
# 2026-09-28). Nonzero values that still print 0.000 are counted in ZERO_PRINTS and reported.
ZERO_PRINTS = []


def _f3(x, where=""):
    v = float(x)
    s = f"{v:,.3f}"
    if float(s.replace(",", "")) == 0.0:
        if v != 0.0 and where:
            ZERO_PRINTS.append((where, v))
        s = "0.000"
    return s


def _stars(p):
    if p is None:
        return ""
    p = float(p)
    return "***" if p < 0.01 else "**" if p < 0.05 else "*" if p < 0.10 else ""


def _display_unit(v):
    """(multiplier, unit string) for a regressor; `_natl` variants share the base unit."""
    base = v[:-5] if v.endswith("_natl") else v
    return _DISPLAY_UNITS.get(base, (1.0, ""))


def _label(v):
    """Row label WITHOUT a bracketed unit (units are stated in the prose above the table); the
    display scaling from _DISPLAY_UNITS still applies in _cell()."""
    return LABELS.get(v, v.replace("_", " "))


def _colkey(k, suffix):
    return f"k{k}_{K_LABELS[k]}_{suffix}"


def _cell(res, v, lhs=1.0):
    """Formatted cell. `lhs` is the dependent-variable display multiplier of the deposit type
    (bbl_polfunc._lhs_display: spread 100 = pp, k=5 spread 10,000 = basis points; rate 100) and
    MUST be applied here as well as to Mean dep. var. -- the .tex fragments scale by lhs * unit,
    and without it the .md prints raw fraction coefficients for the same regression."""
    coefs = res.get("coefficients", {})
    if v not in coefs:
        return ""
    mult = _display_unit(v)[0] * lhs
    c = float(coefs[v]) * mult; se = float(res["std_errors"][v]) * mult; p = res["pvalues"].get(v)
    stars = _stars(p).replace("*", r"\*")
    return f"{_f3(c, v)}{stars} ({_f3(se, v + ' SE')})"


def _variant_cell(res, base, lhs=1.0):
    for v in (base, base + "_natl"):
        if v in res.get("coefficients", {}):
            return _cell(res, v, lhs)
    return ""


def _panel_rows(summary, k, lhs=1.0):
    col_res = [summary.get(_colkey(k, s), {}) for s in COLS]
    demo_all = set(DEMO_BASES) | {d + "_natl" for d in DEMO_BASES}
    order, seen = [], set()
    for res in col_res:
        for v in res.get("coefficients", {}):
            if v in demo_all or v in seen or v in _SEGMENT_VARS:
                continue
            order.append(v); seen.add(v)
    rows = []
    for v in order:
        rows.append("| " + _label(v) + " | " + " | ".join(_cell(r, v, lhs) for r in col_res) + " |")
    # Demographics are reported as a Yes/No indicator row (see build_table), matching the main
    # .tex fragment; the coefficient-by-coefficient version lives in the _segment companion .tex.
    return rows


def build_table(summary, cfg_units):
    lines = ["| Regressor | " + " | ".join(COL_HEADERS) + " |", "|---|---|---|---|"]
    for k in (4, 5):
        lhs = _lhs_display(k, cfg_units)
        lines.append(f"| **{K_TITLES[k]}, {_lhs_unit_name(k, cfg_units)}** | | | |")
        lines.extend(_panel_rows(summary, k, lhs))
        seg = ["Yes" if any(v in summary.get(_colkey(k, s), {}).get("coefficients", {})
                            for v in _SEGMENT_VARS) else "No" for s in COLS]
        lines.append("| Segment FE | " + " | ".join(seg) + " |")
        demo_all = set(DEMO_BASES) | {d + "_natl" for d in DEMO_BASES}
        demo = ["Yes" if any(v in summary.get(_colkey(k, s), {}).get("coefficients", {})
                             for v in demo_all) else "No" for s in COLS]
        lines.append("| Demographics | " + " | ".join(demo) + " |")
        mdv = [summary.get(_colkey(k, s), {}).get("mean_depvar") for s in COLS]
        lines.append("| Mean dep. var. | " + " | ".join(
            _f3(x * lhs, f'k={k} mean') if x is not None else "" for x in mdv) + " |")
        r2 = [summary.get(_colkey(k, s), {}).get("r_squared") for s in COLS]
        lines.append("| R² | " + " | ".join(_f3(x) if x is not None else "" for x in r2) + " |")

    def stat(key, fmt):
        vals = [summary.get(_colkey(4, s), {}).get(key) for s in COLS]
        return " | ".join(fmt(v) if v is not None else "" for v in vals)
    lines.append("| **Observations** | " + stat("n_obs", lambda x: f"{int(x):,}") + " |")
    lines.append("| Clusters (G) | " + stat("n_clusters", lambda x: f"{int(x):,}") + " |")
    lines.append("| Eff. clusters (G*) | " + stat("G_star", lambda x: _f3(x)) + " |")
    return "\n".join(lines)


def _stat(summary, col, key, nd):
    """Cluster-structure stat for a column (read off k=4; identical across k)."""
    v = summary.get(_colkey(4, col), {}).get(key)
    if v is None:
        return "—"
    return f"{int(v):,}" if nd == 0 else _f3(v)


def _intro(depvar, summary, cfg):
    def r2(k, s):
        return summary.get(_colkey(k, s), {}).get("r_squared")
    shared = (
        "Eight regressions — two endogenous deposit types (k=4 Time/CDB, k=5 Prepaid) × four "
        "firm-type/demographic specifications — estimated by OLS over the 2016–2024 window. **B and D "
        "firms are estimated separately, each with its own coefficient vector**; downstream, Step 2 takes "
        "**B → the `B-type` column and D → the `D (natl. demo.)` column** (the `D (no demo.)` column asks whether the national demographics do any work). A pooled B=D specification is also estimated but not shown. "
        "Standard errors are a score/multiplier **WCB at the conglomerate level** — "
        "the same scheme and clustering unit as the sleepiness and BLP stages, so every SE in the paper "
        "is produced one way; G and G\* are reported as the cluster-paucity statistics that motivate it, "
        "not as the inference. That paucity is severe on the B side: with conglomerate clusters the "
        f"B-type column has only G={_stat(summary,'B','n_clusters',0)} nominal and "
        f"**G\*≈{_stat(summary,'B','G_star',1)} effective** clusters. Webb weights are used for exactly "
        "this regime; read the B column's inference with that in mind. "
        "The accounting ratios (Basel index, equity ratio, cost ratios, asset return, NPL provisions, "
        "credit/assets) are **winsorized at 1/99 within firm type** — the reported D-firm balance "
        "sheets contain near-zero-denominator artifacts (Basel index up to 16,070 against a B-firm "
        "max of 7.10) that otherwise drive both the point estimates and the bootstrap SEs. "
        "Coefficients at three decimals, standard errors in parentheses, significance \*\*\*/\*\*/\* at 1/5/10%. "
        "**Demographic units are pinned to the sleepiness tables** so those coefficients are comparable "
        "across the two: GDP *per capita* in 10k R$ and CadUnico families in 100s per 1k (the two "
        "variables the demand prep rescales), population shares as raw fractions, mobile lines per 100 "
        "inhabitants; Pix users (absent there) per 100 per 1k. **All other ratios are in percentage "
        "points** — equity, Basel, cost, wholesale, LCI/LCA, asset return, NPL provisions, credit/assets "
        "and the risk-free rate — so a coefficient is the effect of a 1pp move rather than of an "
        "unattainable 0→100% change. "
        "Rescaling is a change of units only: it leaves the fit, t-statistics and stars untouched "
        "(verified — R² and p-values identical to 1e-14)."
    )
    if depvar == "spread":
        head = (
            "The dependent variable is the **compounded annual deposit spread** "
            "ρ = (1+r^f)⁴ − (1+r^dep)⁴ of the quarterly rates, the definition of the demand price "
            "(the policy fed to BBL Step 2), in percentage points for k=4 and in **basis points for "
            "k=5**, whose spread is itself about zero. "
            f"The fit is asymmetric — B-firm CDB R²={r2(4,'B'):.2f}, B-firm prepaid R²={r2(5,'B'):.2f}, "
            f"but the digital/national D regressions fit prepaid poorly (R²≈{r2(5,'D_optB'):.02f}). "
        )
    else:
        head = (
            "The dependent variable is the **annualized deposit rate** r^dep,ann = (1+r^dep_qoq)⁴−1 "
            "(same regressors and samples as the spread table in §2.6; a robustness view that prices "
            "the *level* banks pay rather than the markdown). Since the panel builds "
            "spread_ann = (1+r^f)⁴ − (1+r^dep)⁴ exactly, this is the deposit-rate half of that identity. "
            f"Prepaid deposit rates are **nearly deterministic** (R²≈{r2(5,'B'):.2f} across all specs) — "
            "prepaid accounts pay a near-constant rate — whereas CDB rates are moderately explained "
            f"(B R²={r2(4,'B'):.2f}, D R²={r2(4,'D_optB'):.2f}). Note the contrast with §2.6: prepaid "
            "*rates* are easy to fit precisely because they barely move, yet prepaid *spreads* are not, "
            "since the spread is dominated by the moving risk-free rate. "
        )
    ptr = (
        "The same estimates are the paper fragments, split by deposit type: "
        f"`{cfg['tex_pattern'].format(k=4)}` (`{cfg['tab_base']}_k4`) and "
        f"`{cfg['tex_pattern'].format(k=5)}` (`{cfg['tab_base']}_k5`), each `\\input`-able."
    )
    return head + shared + " " + ptr + "\n"


def build_section(depvar, summary):
    cfg = VARIANTS[depvar]
    heading = cfg["heading"]
    intro = _intro(depvar, summary, cfg)
    # LHS display multipliers per deposit type, imported from the estimator so the .md and .tex
    # agree by construction (spread: pp, k=5 in basis points; rate: pp).
    cfg_units = _CFG_SPREAD if depvar == "spread" else _CFG_RATE
    tbl = build_table(summary, cfg_units)
    return f"{cfg['start']}\n{heading}\n\n{intro}\n{tbl}\n{cfg['end']}"


def main():
    ap = argparse.ArgumentParser(description="Regenerate a §2.6/§2.7 policy-function table in counterfactuals_plan.md")
    ap.add_argument("--depvar", choices=["spread", "rate"], default="spread",
                    help="which regressand variant (default spread → §2.6; rate → §2.7)")
    args = ap.parse_args()
    cfg = VARIANTS[args.depvar]

    summary_path = SUMMARY_DIR / f"{cfg['summary_prefix']}_summary.json"
    if not summary_path.exists():
        raise SystemExit(f"[FATAL] summary not found: {summary_path}\n"
                         f"  Run bbl_polfunc.py --depvar {args.depvar} first.")
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    block = build_section(args.depvar, summary)

    md = MD_PATH.read_text(encoding="utf-8")
    if cfg["start"] in md and cfg["end"] in md:
        pre = md[:md.index(cfg["start"])]
        post = md[md.index(cfg["end"]) + len(cfg["end"]):]
        md = pre + block + post
        action = "refreshed"
    else:
        if ANCHOR not in md:
            raise SystemExit(f"[FATAL] anchor not found: {ANCHOR!r}")
        idx = md.index(ANCHOR)
        head = md[:idx].rstrip()
        if head.endswith("---"):
            head = head[:-3].rstrip()
        md = head + "\n\n" + block + "\n\n---\n\n" + md[idx:]
        action = "inserted"

    MD_PATH.write_text(md, encoding="utf-8", newline="\n")
    if ZERO_PRINTS:
        print(f"[display] {len(ZERO_PRINTS)} nonzero value(s) print as 0.000 at three decimals "
              f"(not rescaled): " + ", ".join(f"{w} {v:.2e}" for w, v in ZERO_PRINTS))
    n_rows = block.count("\n| ")
    print(f"[OK] {args.depvar} policy-function section {action} in {MD_PATH.name} "
          f"({n_rows} table rows).")


if __name__ == "__main__":
    main()
