#!/usr/bin/env python3
"""
make_polfunc_md_table.py
========================
Regenerate a policy-function results section of `counterfactuals_plan.md` from the
BBL Step-1 estimation summary JSON. Reproducible counterpart of the paper fragments
`polfunc_spec{spec}.tex` / `polfunc_rate_spec{spec}.tex` (written by
estimation_bbl_1_polfunc.py). Reads the CURRENT .md, replaces the block between
sentinels, and writes the WHOLE .md back (narrative untouched).

Two variants, keyed by --depvar (matching the estimator's --depvar):
    spread : §2.6, LHS = QoQ deposit spread  (the policy fed to Step 2)   [default]
    rate   : §2.7, LHS = annualized deposit rate (1+rate_qoq)^4-1

    python make_polfunc_md_table.py                 # spread, spec 12
    python make_polfunc_md_table.py --depvar rate    # rate, spec 12
"""
import argparse
import json
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]           # .../Open-Finance
SUMMARY_DIR = _ROOT / "BCB" / "Egan_et_al_2025_Rep" / "processed" / "ESTIMATION_OUTPUT" / "COST_POLFUNC"
MD_PATH = _ROOT / "Drafts" / "Deposit Competition" / "counterfactuals_plan.md"
ANCHOR = "## 3. The execution plan (easiest → hardest)"   # §2.6/§2.7 are inserted just before §3

K_LABELS = {4: "Time_CDB", 5: "Prepaid"}
K_TITLES = {4: "Panel A: Time deposits / CDB (k=4)", 5: "Panel B: Prepaid accounts (k=5)"}
COLS = ["B", "D_optA", "D_optB", "pooled_optC"]
COL_HEADERS = ["B-type", "D (no demo.)", "D (natl. demo.)", "Pooled (B=D)"]

DEMO_BASES = ["gdp_per_capita", "fraction_65plus", "fraction_young",
              "pix_users_pf_per1000", "connections_per100", "branches_per1000",
              "cadunico_families_per1000"]

LABELS = {
    "const": "Constant",
    "log_total_assets_lag": "Log total assets (t−1)",
    "equity_ratio_lag": "Equity ratio (t−1)",
    "has_ip": "Has IP subsidiary",
    "asset_return_qoq_lag": "Asset return (QoQ, t−1)",
    "npl_provision_ratio_lag": "NPL provisions ratio (t−1)",
    "credit_assets_lag": "Credit / assets (t−1)",
    "seg_S2": "Segment S2", "seg_S3": "Segment S3", "seg_S4": "Segment S4", "seg_S5": "Segment S5",
    "personnel_cost_ratio_lag": "Personnel cost ratio (t−1)",
    "admin_cost_ratio_lag": "Admin cost ratio (t−1)",
    "tax_cost_ratio_lag": "Tax cost ratio (t−1)",
    "indice_basileia_lag": "Basel index (bp, t−1)",
    "wholesale_ratio_lag": "Wholesale ratio (t−1)",
    "lci_lca_ratio_lag": "LCI/LCA ratio (t−1)",
    "risk_free_qoq": "Risk-free rate (QoQ)",
    "log_total_assets_lag_sq": "Log total assets²",
    "equity_ratio_lag_sq": "Equity ratio²",
    "risk_free_qoq_sq": "Risk-free rate²",
    "gdp_per_capita": "GDP per capita",
    "fraction_65plus": "Fraction 65+",
    "fraction_young": "Fraction young",
    "pix_users_pf_per1000": "Pix users (per 1k)",
    "connections_per100": "Broadband (per 100)",
    "branches_per1000": "Branches (per 1k)",
    "cadunico_families_per1000": "CadUnico families (per 1k)",
}

# Per-variant configuration.
VARIANTS = {
    "spread": {
        "summary_prefix": "polfunc",
        "start": "<!-- POLFUNC-SECTION:START (generated by make_polfunc_md_table.py — regenerate, do not hand-edit) -->",
        "end": "<!-- POLFUNC-SECTION:END -->",
        "heading": "### 2.6 The estimated policy function — spread (spec {spec})",
        "tex_pattern": "polfunc_k{k}_spec{spec}.tex",
        "tab_base": "tab:polfunc",
    },
    "rate": {
        "summary_prefix": "polfunc_rate",
        "start": "<!-- POLFUNC-RATE-SECTION:START (generated by make_polfunc_md_table.py --depvar rate — regenerate, do not hand-edit) -->",
        "end": "<!-- POLFUNC-RATE-SECTION:END -->",
        "heading": "### 2.7 The estimated policy function — deposit rate (spec {spec})",
        "tex_pattern": "polfunc_rate_k{k}_spec{spec}.tex",
        "tab_base": "tab:polfunc_rate",
    },
}


def _stars(p):
    if p is None:
        return ""
    p = float(p)
    return "***" if p < 0.01 else "**" if p < 0.05 else "*" if p < 0.10 else ""


def _label(v):
    return LABELS.get(v, v.replace("_", " "))


def _colkey(k, suffix):
    return f"k{k}_{K_LABELS[k]}_{suffix}"


def _cell(res, v):
    coefs = res.get("coefficients", {})
    if v not in coefs:
        return ""
    c = float(coefs[v]); se = float(res["std_errors"][v]); p = res["pvalues"].get(v)
    stars = _stars(p).replace("*", r"\*")
    return f"{c:.4f}{stars} ({se:.4f})"


def _variant_cell(res, base):
    for v in (base, base + "_natl"):
        if v in res.get("coefficients", {}):
            return _cell(res, v)
    return ""


def _panel_rows(summary, k):
    col_res = [summary.get(_colkey(k, s), {}) for s in COLS]
    demo_all = set(DEMO_BASES) | {d + "_natl" for d in DEMO_BASES}
    order, seen = [], set()
    for res in col_res:
        for v in res.get("coefficients", {}):
            if v in demo_all or v in seen:
                continue
            order.append(v); seen.add(v)
    rows = []
    for v in order:
        rows.append("| " + _label(v) + " | " + " | ".join(_cell(r, v) for r in col_res) + " |")
    for base in DEMO_BASES:
        cells = [_variant_cell(r, base) for r in col_res]
        if any(cells):
            rows.append("| " + _label(base) + " | " + " | ".join(cells) + " |")
    return rows


def build_table(summary):
    lines = ["| Regressor | " + " | ".join(COL_HEADERS) + " |", "|---|---|---|---|---|"]
    for k in (4, 5):
        lines.append(f"| **{K_TITLES[k]}** | | | | |")
        lines.extend(_panel_rows(summary, k))
        r2 = [summary.get(_colkey(k, s), {}).get("r_squared") for s in COLS]
        lines.append("| R² | " + " | ".join(f"{x:.4f}" if x is not None else "" for x in r2) + " |")

    def stat(key, fmt):
        vals = [summary.get(_colkey(4, s), {}).get(key) for s in COLS]
        return " | ".join(fmt(v) if v is not None else "" for v in vals)
    lines.append("| **Observations** | " + stat("n_obs", lambda x: f"{int(x):,}") + " |")
    lines.append("| Clusters (G) | " + stat("n_clusters", lambda x: f"{int(x)}") + " |")
    lines.append("| Eff. clusters (G*) | " + stat("G_star", lambda x: f"{float(x):.1f}") + " |")
    return "\n".join(lines)


def _intro(depvar, summary, spec, cfg):
    def r2(k, s):
        return summary.get(_colkey(k, s), {}).get("r_squared")
    shared = (
        "Eight regressions — two endogenous deposit types (k=4 Time/CDB, k=5 Prepaid) × four "
        "firm-type/demographic specifications — estimated by OLS over the 2016–2024 window. **B and D "
        "firms are estimated separately, each with its own coefficient vector** (Option C pools them); "
        "downstream, Step 2 takes **B → the `B-type` column and D → the `D (natl. demo.)` column**. "
        "Coefficients 4-decimal, standard errors in parentheses, significance ***/**/* at 1/5/10%. Some "
        "regressors are on raw scales (GDP per capita in R$, Basel index in bp), so their coefficients "
        "are small by construction and may display as `0.0000` while significant."
    )
    if depvar == "spread":
        head = (
            "The dependent variable is the observed **quarterly deposit spread** "
            "ρ = r^f − r^dep (the policy fed to BBL Step 2). "
            f"The fit is asymmetric — B-firm CDB R²={r2(4,'B'):.2f}, B-firm prepaid R²={r2(5,'B'):.2f}, "
            f"but the digital/national D regressions fit prepaid poorly (R²≈{r2(5,'D_optB'):.02f}). "
        )
    else:
        head = (
            "The dependent variable is the **annualized deposit rate** r^dep,ann = (1+r^dep_qoq)⁴−1 "
            "(same regressors and samples as the spread table in §2.6; a robustness view that prices "
            "the *level* banks pay rather than the markdown). Since the panel builds "
            "spread_ann = (1+r^f)⁴ − (1+r^dep)⁴ exactly, this is the deposit-rate half of that identity. "
            f"Prepaid deposit rates are **nearly deterministic** (R²≈{r2(5,'B'):.2f} across all specs) — "
            "prepaid accounts pay a near-constant rate — whereas CDB rates are moderately explained "
            f"(B R²={r2(4,'B'):.2f}, D R²={r2(4,'D_optB'):.2f}). Note the contrast with §2.6: prepaid "
            "*rates* are easy to fit precisely because they barely move, yet prepaid *spreads* are not, "
            "since the spread is dominated by the moving risk-free rate. "
        )
    ptr = (
        "The same estimates are the paper fragments, split by deposit type: "
        f"`{cfg['tex_pattern'].format(k=4, spec=spec)}` (`{cfg['tab_base']}_k4`) and "
        f"`{cfg['tex_pattern'].format(k=5, spec=spec)}` (`{cfg['tab_base']}_k5`), each `\\input`-able."
    )
    return head + shared + " " + ptr + "\n"


def build_section(depvar, summary, spec):
    cfg = VARIANTS[depvar]
    heading = cfg["heading"].format(spec=spec)
    intro = _intro(depvar, summary, spec, cfg)
    tbl = build_table(summary)
    return f"{cfg['start']}\n{heading}\n\n{intro}\n{tbl}\n{cfg['end']}"


def main():
    ap = argparse.ArgumentParser(description="Regenerate a §2.6/§2.7 policy-function table in counterfactuals_plan.md")
    ap.add_argument("--spec", default="12", help="spec label (default 12)")
    ap.add_argument("--depvar", choices=["spread", "rate"], default="spread",
                    help="which regressand variant (default spread → §2.6; rate → §2.7)")
    args = ap.parse_args()
    cfg = VARIANTS[args.depvar]

    summary_path = SUMMARY_DIR / f"{cfg['summary_prefix']}_summary_spec_{args.spec}.json"
    if not summary_path.exists():
        raise SystemExit(f"[FATAL] summary not found: {summary_path}\n"
                         f"  Run estimation_bbl_1_polfunc.py --spec {args.spec} --depvar {args.depvar} first.")
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    block = build_section(args.depvar, summary, args.spec)

    md = MD_PATH.read_text(encoding="utf-8")
    if cfg["start"] in md and cfg["end"] in md:
        pre = md[:md.index(cfg["start"])]
        post = md[md.index(cfg["end"]) + len(cfg["end"]):]
        md = pre + block + post
        action = "refreshed"
    else:
        if ANCHOR not in md:
            raise SystemExit(f"[FATAL] anchor not found: {ANCHOR!r}")
        idx = md.index(ANCHOR)
        head = md[:idx].rstrip()
        if head.endswith("---"):
            head = head[:-3].rstrip()
        md = head + "\n\n" + block + "\n\n---\n\n" + md[idx:]
        action = "inserted"

    MD_PATH.write_text(md, encoding="utf-8", newline="\n")
    n_rows = block.count("\n| ")
    print(f"[OK] {args.depvar} policy-function section {action} in {MD_PATH.name} "
          f"({n_rows} table rows, spec {args.spec}).")


if __name__ == "__main__":
    main()
